//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson09___Entity_Framework___Database_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khoa
    {
        public string MaKH { get; set; }
        public string TenKH { get; set; }
    }
}
